export const ProjectShowcases = [
  {
    type: "full-showcase",
    techType: "morden",
    slug: "food-delivery-app",
    title: "Food Delivery App (Zomato clone)",
    description: "Next.js - Tailwind CSS - Jest - React Testing Library",
    image: "/assets/zomato-screenshot.png",
    bgClass: "zomato-bg",
    projectInfo:
      "Developed a responsive restaurant listings web app with Next.js and Tailwind CSS, featuring advanced functionalities like search, sorting, and menu search based on attributes such as price, rating, and cuisine. Utilized Test-Driven Development (TDD) with React Testing Library and Jest, achieving a solid 94% code coverage for enhanced reliability. The project focuses on a seamless user experience through responsive design while emphasizing robust coding practices. With a visually appealing interface and a commitment to code quality, the web app provides an efficient platform for exploring restaurants, ensuring stability and maintainability through rigorous testing principles.",
    code: {
      title: "Go to Code",
      iconImage: "/assets/github-black.svg",
      userName: "satyam95",
      name: "Food-Delivery-App",
      link: "https://github.com/satyam95/Food-Delivery-App",
    },
    demo: {
      title: "Go to Demo",
      name: "food-delivery",
      userName: "satyam95",
      link: "https://food-delivery-satyam95.vercel.app/",
      iconImage: "/assets/vercel.svg",
    },
    screenshorts: [
      "/assets/zomato-screenshot.png",
      "/assets/zomato/listing-page.png",
      "/assets/zomato/filter.png",
      "/assets/zomato/resturant.png",
      "/assets/zomato/menu.png",
      "/assets/zomato/menu-filter.png",
    ],
  },
  {
    type: "full-showcase",
    techType: "morden",
    slug: "ecommerce-app",
    title: "Ecommerce App (Flipkart clone)",
    description:
      "Next.js - Tailwind CSS - Redux/Redux Toolkit - Next Auth - Stripe Payment Gateway",
    image: "/assets/flipkar-screenshot.png",
    bgClass: "flipkart-bg",
    projectInfo:
      "Built with Next.js and styled using Tailwind CSS, this web app closely mirrors Flipkart's design and functionality. It replicates an appealing homepage, category pages, an intuitive cart system, and secure Stripe payments. The search feature and product pages closely resemble Flipkart's user experience. Authentication is powered by NextAuth.js, ensuring user security. Additionally, it offers advanced product filtering based on product ratings, brands, and availability, along with a user-friendly sorting feature, allowing users to sort products based on price.",
    code: {
      title: "Go to Code",
      iconImage: "/assets/github-black.svg",
      userName: "satyam95",
      name: "flipkart_clone",
      link: "https://github.com/satyam95/flipkart_clone",
    },
    demo: {
      title: "Go to Demo",
      name: "flipkart_clone",
      userName: "satyam95",
      link: "https://flipkart-clone-satyam95.vercel.app/",
      iconImage: "/assets/vercel.svg",
    },
    screenshorts: [
      "/assets/flipkar-screenshot.png",
      "/assets/flipkart/login.png",
      "/assets/flipkart/filter.png",
      "/assets/flipkart/list-view.png",
      "/assets/flipkart/product-page.png",
      "/assets/flipkart/cart-page.png",
    ],
  },
  {
    type: "half-showcase",
    techType: "morden",
    slug: "laundry-app",
    title: "Laundry App - React Native",
    description:
      "React Native - Firebase Authentication - Firebase Store - Redux/Redux Toolkit",
    image: "/assets/laundry-app.png",
    bgClass: "",
    projectInfo:
      "Built with React Native, this project underscores my expertise in mobile development. Employing Redux/Redux Toolkit for robust state management and Firebase for secure user authentication, the React Native Laundry App offers a seamless user onboarding experience through the registration/login interface. The app's distinctive cart functionality allows users to effortlessly organize laundry items, culminating in a streamlined order completion process where pickup details like address and time are effortlessly input. This project showcases my commitment to blending innovation with practicality, providing users with an elevated and efficient laundry management experience—a testament to my skills and dedication in mobile development.",
    code: {
      title: "Go to Code",
      iconImage: "/assets/github-black.svg",
      userName: "satyam95",
      name: "laundry-app",
      link: "",
    },
    demo: {
      title: "Go to Demo",
      name: "",
      userName: "satyam95",
      link: "laundry-app",
      iconImage: "/assets/vercel.svg",
    },
    screenshorts: ["/assets/laundry-app.png"],
  },
  {
    type: "half-showcase",
    techType: "morden",
    slug: "landing-page",
    title: "Responsive Landing Page - Next.js",
    description: "Next.js - Tailwind CSS - Responsive Design Layout",
    image: "/assets/travel-lp.png",
    bgClass: "",
    projectInfo:
      "Crafted with Next.js and Tailwind CSS, this mobile-first landing page seamlessly adapts to various screen sizes for optimal user experience. Our responsive design ensures a visually stunning and intuitive interface, combining cutting-edge technology with sleek styling to captivate visitors on any device.",
    code: {
      title: "Go to Code",
      iconImage: "/assets/github-black.svg",
      userName: "satyam95",
      name: "travel-lp",
      link: "https://github.com/satyam95/travel-lp",
    },
    demo: {
      title: "Go to Demo",
      name: "travel-lp",
      userName: "satyam95",
      link: "https://travel-lp-satyam95.vercel.app/",
      iconImage: "/assets/vercel.svg",
    },
    screenshorts: ["/assets/travel-lp.png"],
  },
  {
    type: "wp-showcase",
    slug: "wp-elements-plus",
    title: "WP Elements Plus - Customize WP Bakery with Ease.",
    description: "",
    image: "/assets/wp/wp-elements-plus.png",
    bgClass: "",
    projectInfo:
      "Elevate your website's design with our custom WordPress plugin, expanding the functionality of WP Bakery Page Builder with seven lightweight and versatile custom elements. These elements are meticulously crafted for simplicity, allowing users to customize them effortlessly based on individual preferences.",
    code: {
      title: "Go to Code",
      iconImage: "/assets/github-black.svg",
      userName: "satyam95",
      name: "wp-elements-plus",
      link: "https://github.com/satyam95/wp-elements-plus",
    },
    demo: {
      title: "Go to Demo",
      name: "wp-elements-plus",
      userName: "satyam95.tech",
      link: "https://wp-elements-plus.satyam95.tech/",
      iconImage: "/assets/wordpress.svg",
    },
    screenshorts: [
      "/assets/wp-element-plus/main-screenshot.png",
      "/assets/wp-element-plus/custom-list-block.png",
      "/assets/wp-element-plus/logo-slider.png",
      "/assets/wp-element-plus/team-block.png",
      "/assets/wp-element-plus/testimonial-block.png",
      "/assets/wp-element-plus/infobox-card.png",
      "/assets/wp-element-plus/usp-pointer-card.png",
      "/assets/wp-element-plus/news-article-card.png",
    ],
  },
  {
    type: "wp-showcase",
    slug: "xspark-wp-theme",
    title: "XSpark - Custom Wordpress theme.",
    description: "",
    image: "/assets/xspark/hero-sec.png",
    bgClass: "",
    projectInfo:
      "XSpark is a meticulously crafted custom WordPress theme designed to provide a unique and tailored experience for website owners. This theme stands out with its custom support for essential elements such as logos, menus, footer columns, and copyright text. Developed with a keen focus on performance and responsiveness, XSpark ensures a seamless user experience across various devices. XSpark offers specialized blog templates, including a captivating Single Blog Page, an organized Archive Page for easy navigation through past posts, and a visually cohesive main Blog Page.",
    code: {
      title: "Go to Code",
      iconImage: "/assets/github-black.svg",
      userName: "satyam95",
      name: "xspark",
      link: "https://github.com/satyam95/xspark",
    },
    demo: {
      title: "Go to Demo",
      name: "xspark",
      userName: "satyam95.tech",
      link: "https://xspark.satyam95.tech/",
      iconImage: "/assets/wordpress.svg",
    },
    screenshorts: [
      "/assets/xspark/hero-sec.png",
      "/assets/xspark/info-section.png",
      "/assets/xspark/review-sec.png",
      "/assets/xspark/archive-page.png",
      "/assets/xspark/blog-page.png",
    ],
  },
];
